"""Utility helpers to seed predictable sample data into the database."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app import create_app
from app.config import DevelopmentConfig
from app.extensions import db
from app.models import Project, User

DEFAULT_PASSWORD = "ChangeMe123!"

USER_TEMPLATES = [
    ("Alex Anderson", "manager"),
    ("Blake Brooks", "employee"),
    ("Casey Campbell", "employee"),
    ("Dana Davis", "manager"),
    ("Elliott Edwards", "employee"),
]

PROJECT_TITLES = [
    "Aurora Expansion",
    "Beacon Rollout",
    "Catalyst Improvements",
    "Momentum Planning",
    "Summit Launch",
]


def _user_payload(index: int) -> dict[str, str]:
    """Return a deterministic user payload for the given index."""

    base_name, role = USER_TEMPLATES[index % len(USER_TEMPLATES)]
    iteration = index // len(USER_TEMPLATES)
    name = f"{base_name} {iteration + 1}" if iteration else base_name
    email_slug = name.lower().replace(" ", ".")
    email = f"{email_slug}@example.com"
    return {"name": name, "email": email, "role": role}


def _project_payload(index: int) -> tuple[str, str]:
    """Return a deterministic project name and description."""

    base_title = PROJECT_TITLES[index % len(PROJECT_TITLES)]
    iteration = index // len(PROJECT_TITLES)
    name = f"{base_title} #{iteration + 1}" if iteration else base_title
    description = f"Sample project generated by the seed script: {name}."
    return name, description


def seed_database(
    num_users: int = 5,
    num_projects: int = 5,
    *,
    default_password: str = DEFAULT_PASSWORD,
) -> tuple[int, int]:
    """Create a batch of predictable users and projects."""

    if num_users < 0 or num_projects < 0:
        raise ValueError("Number of users and projects must be non-negative.")

    new_users: list[User] = []
    for index in range(num_users):
        payload = _user_payload(index)
        if User.query.filter_by(email=payload["email"]).first():
            continue
        user = User(**payload)
        user.set_password(default_password)
        db.session.add(user)
        new_users.append(user)

    db.session.flush()
    all_users = User.query.order_by(User.id).all()
    managers = [user for user in all_users if user.role == "manager"] or all_users

    created_projects = 0
    if not managers and num_projects:
        db.session.commit()
        return len(new_users), created_projects

    for index in range(num_projects):
        name, description = _project_payload(index)
        if Project.query.filter_by(name=name).first():
            continue
        owner = managers[index % len(managers)] if managers else None
        project = Project(
            name=name,
            description=description,
            created_by=owner.id if owner else None,
        )
        db.session.add(project)
        created_projects += 1

    db.session.commit()
    return len(new_users), created_projects


def main() -> None:
    """CLI entry point when invoked as a standalone script."""

    parser = argparse.ArgumentParser(
        description="Seed deterministic users and projects into the database."
    )
    parser.add_argument("--users", type=int, default=5, help="Number of users to create.")
    parser.add_argument(
        "--projects",
        type=int,
        default=5,
        help="Number of projects to create.",
    )
    parser.add_argument(
        "--password",
        default=DEFAULT_PASSWORD,
        help="Password assigned to created users.",
    )
    args = parser.parse_args()

    app = create_app(DevelopmentConfig)
    with app.app_context():
        db.create_all()
        created_users, created_projects = seed_database(
            num_users=args.users,
            num_projects=args.projects,
            default_password=args.password,
        )
        print(
            f"Seeded {created_users} users and {created_projects} projects "
            f"(requested {args.users} users, {args.projects} projects)."
        )


if __name__ == "__main__":
    main()
